### ISSUE TITLE
获取不到插件策略类

### ISSUE THREAD

**Issue by michal-fang** [Rajithkonara/spring-plugin#1]
![image](https://user-images.githubusercontent.com/96645851/163129776-1aa3a859-139e-4289-9a72-417d34c05c4a.png)

**Comment by Rajithkonara** [comment]
@michal-fang  Did you add WeChatPay to PaymentMethod Enum ?

**Comment by michal-fang** [comment]
thank you, I got it, thanks again!


***@***.***
 
发件人： Rajithkonara (RK)
发送时间： 2022-04-14 11:23
收件人： Rajithkonara/spring-plugin
抄送： michal-fang; Mention
主题： Re: [Rajithkonara/spring-plugin] 获取不到插件策略类 (Issue #1)
@michal-fang Did you add WeChatPay to PaymentMethod Enum ?

**Comment by Rajithkonara** [comment]
Closing this issue, hence @michal-fang got it fixed
